# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef/fedora-21"

  #config.vm.network "public_network", ip: "192.168.0.6", 
  #   bridge: 'en0: Ethernet', :adapter => 2 

  config.vm.provision "ansible" do |ansible| 
     ansible.playbook = "playbook.yml"
  end
end
